#pragma once

enum KeyboardKey {
    kKeyA,  // Letters
    kKeyB,
    kKeyC,
    kKeyD,
    kKeyE,
    kKeyF,
    kKeyG,
    kKeyH,
    kKeyI,
    kKeyJ,
    kKeyK,
    kKeyL,
    kKeyM,
    kKeyN,
    kKeyO,
    kKeyP,
    kKeyQ,
    kKeyR,
    kKeyS,
    kKeyT,
    kKeyU,
    kKeyV,
    kKeyW,
    kKeyX,
    kKeyY,
    kKeyZ,
    kKey0,  // Numbers
    kKey1,
    kKey2,
    kKey3,
    kKey4,
    kKey5,
    kKey6,
    kKey7,
    kKey8,
    kKey9,
    kKeyBackspace,  // Modifiers, etc.
    kKeyLeftAlt,
    kKeyLeftShift,
    kKeyReturn,
    kKeyRightAlt,
    kKeyRightShift,
    kKeyTab,
    kKeyAmpersand,  // Special Characters
    kKeyAsterisk,
    kKeyAt,
    kKeyBackslash,
    kKeyBackQuote,
    kKeyCaret,
    kKeyColon,
    kKeyComma,
    kKeyDollar,
    kKeyEquals,
    kKeyExclaim,
    kKeyGreater,
    kKeyHash,
    kKeyLeftBracket,
    kKeyLeftParen,
    kKeyLess,
    kKeyMinus,
    kKeyPercent,
    kKeyPeriod,
    kKeyPlus,
    kKeyQuestion,
    kKeyDoubleQuote,
    kKeyRightBracket,
    kKeyRightParen,
    kKeySemicolon,
    kKeyUnderscore
};

enum ControllerButton {
    kButtonInvalid,
    kButtonA,
    kButtonB,
    kButtonX,
    kButtonY,
    kButtonBack,
    kButtonGuide,
    kButtonStart,
    kButtonLeftStick,
    kButtonRightStick,
    kButtonLeftShoulder,
    kButtonRightShoulder,
    kButtonDpadUp,
    kButtonDpadDown,
    kButtonDpadLeft,
    kButtonDpadRight,
    kButtonMax
};

enum MouseButton {
    kMouseLeft,
    kMouseMiddle,
    kMouseRight,
    kMouse4,
    kMouse5
};
